src/java/entity/Kategorija.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author JRadakovic
 */
@Entity
@Table(name = "kategorija")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Kategorija.findAll", query = "SELECT k FROM Kategorija k"),
    @NamedQuery(name = "Kategorija.findById_Kategorija", query = "SELECT k FROM Kategorija k WHERE k.id_Kategorija = :id_Kategorija"),
    @NamedQuery(name = "Kategorija.findByNaziv_Kategorije", query = "SELECT k FROM Kategorija k WHERE k.naziv_Kategorije = :naziv_Kategorije")})
public class Kategorija implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id_Kategorija")
    private Integer id_Kategorija;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "naziv_Kategorije")
    private String naziv_Kategorije;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "kategorija_id_INT")
    private Collection<Proizvod> proizvodCollection;

    public Kategorija() {
    }

    public Kategorija(Integer id_Kategorija) {
        this.id_Kategorija = id_Kategorija;
    }

    public Kategorija(Integer id_Kategorija, String naziv_Kategorije) {
        this.id_Kategorija = id_Kategorija;
        this.naziv_Kategorije = naziv_Kategorije;
    }

    public Integer getId_Kategorija() {
        return id_Kategorija;
    }

    public void setId_Kategorija(Integer id_Kategorija) {
        this.id_Kategorija = id_Kategorija;
    }

    public String getNaziv_Kategorije() {
        return naziv_Kategorije;
    }

    public void setNaziv_Kategorije(String naziv_Kategorije) {
        this.naziv_Kategorije = naziv_Kategorije;
    }

    @XmlTransient
    public Collection<Proizvod> getProizvodCollection() {
        return proizvodCollection;
    }

    public void setProizvodCollection(Collection<Proizvod> proizvodCollection) {
        this.proizvodCollection = proizvodCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id_Kategorija != null ? id_Kategorija.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Kategorija)) {
            return false;
        }
        Kategorija other = (Kategorija) object;
        if ((this.id_Kategorija == null && other.id_Kategorija != null) || (this.id_Kategorija != null && !this.id_Kategorija.equals(other.id_Kategorija))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entity.Kategorija[ id_Kategorija=" + id_Kategorija + " ]";
    }
    
}

src/java/entity/Porudzbina.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author ASUS
 */
@Entity
@Table(name = "porudzbina")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Porudzbina.findAll", query = "SELECT p FROM Porudzbina p"),
    @NamedQuery(name = "Porudzbina.findById_Porudzbina", query = "SELECT p FROM Porudzbina p WHERE p.id_Porudzbina = :id_Porudzbina"),
    @NamedQuery(name = "Porudzbina.findByRacun_Porudzbine", query = "SELECT p FROM Porudzbina p WHERE p.racun_Porudzbine = :racun_Porudzbine"),
    @NamedQuery(name = "Porudzbina.findByVreme_kreiranja_Porudzbine", query = "SELECT p FROM Porudzbina p WHERE p.vreme_kreiranja_Porudzbine = :vreme_kreiranja_Porudzbine"),
    @NamedQuery(name = "Porudzbina.findByBroj_potvrde_Porudzbine", query = "SELECT p FROM Porudzbina p WHERE p.broj_potvrde_Porudzbine = :broj_potvrde_Porudzbine")})
public class Porudzbina implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id_Porudzbina")
    private Integer id_Porudzbina;
    // @Max(value=?)  @Min(value=?)//if you know range of your decimal fields consider using these annotations to enforce field validation
    @Basic(optional = false)
    @NotNull
    @Column(name = "racun_Porudzbine")
    private BigDecimal racun_Porudzbine;
    @Basic(optional = false)
    @NotNull
    @Column(name = "vreme_kreiranja_Porudzbine")
    @Temporal(TemporalType.TIMESTAMP)
    private Date vreme_kreiranja_Porudzbine;
    @Basic(optional = false)
    @NotNull
    @Column(name = "broj_potvrde_Porudzbine")
    private int broj_potvrde_Porudzbine;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "porudzbina")
    private Collection<NaruceniProizvod> naruceni_ProizvodCollection;
    @JoinColumn(name = "Kupac_id_Kupac", referencedColumnName = "id_Kupac")
    @ManyToOne(optional = false)
    private Kupac kupac_id_Kupac;

    public Porudzbina() {
    }

    public Porudzbina(Integer id_Porudzbina) {
        this.id_Porudzbina = id_Porudzbina;
    }

    public Porudzbina(Integer id_Porudzbina, BigDecimal racun_Porudzbine, Date vreme_kreiranja_Porudzbine, int broj_potvrde_Porudzbine) {
        this.id_Porudzbina = id_Porudzbina;
        this.racun_Porudzbine = racun_Porudzbine;
        this.vreme_kreiranja_Porudzbine = vreme_kreiranja_Porudzbine;
        this.broj_potvrde_Porudzbine = broj_potvrde_Porudzbine;
    }

    public Integer getIdPorudzbina() {
        return id_Porudzbina;
    }

    public void setIdPorudzbina(Integer id_Porudzbina) {
        this.id_Porudzbina = id_Porudzbina;
    }

    public BigDecimal getRacunPorudzbine() {
        return racun_Porudzbine;
    }

    public void setRacunPorudzbine(BigDecimal racun_Porudzbine) {
        this.racun_Porudzbine = racun_Porudzbine;
    }

    public Date getVremekreiranjaPorudzbine() {
        return vreme_kreiranja_Porudzbine;
    }

    public void setVremekreiranjaPorudzbine(Date vreme_kreiranja_Porudzbine) {
        this.vreme_kreiranja_Porudzbine = vreme_kreiranja_Porudzbine;
    }

    public int getBrojpotvrdePorudzbine() {
        return broj_potvrde_Porudzbine;
    }

    public void setBrojpotvrdePorudzbine(int broj_potvrde_Porudzbine) {
        this.broj_potvrde_Porudzbine = broj_potvrde_Porudzbine;
    }

    @XmlTransient
    public Collection<NaruceniProizvod> getNaruceniProizvodCollection() {
        return naruceni_ProizvodCollection;
    }

    public void setNaruceniProizvodCollection(Collection<NaruceniProizvod> naruceni_ProizvodCollection) {
        this.naruceni_ProizvodCollection = naruceni_ProizvodCollection;
    }

    public Kupac getKupacidKupac() {
        return kupac_id_Kupac;
    }

    public void setKupacidKupac(Kupac kupac_id_Kupac) {
        this.kupac_id_Kupac = kupac_id_Kupac;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id_Porudzbina != null ? id_Porudzbina.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Porudzbina)) {
            return false;
        }
        Porudzbina other = (Porudzbina) object;
        if ((this.id_Porudzbina == null && other.id_Porudzbina != null) || (this.id_Porudzbina != null && !this.id_Porudzbina.equals(other.id_Porudzbina))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "entity.Porudzbina[ id_Porudzbina=" + id_Porudzbina + " ]";
    }
    
}

web/WEB-INF/view/kategorija.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="sql" uri="http://java.sun.com/jsp/jstl/sql"%>

  
<!DOCTYPE html>
<c:set var="view" value="/kategorija" scope="session" />
<html>
        <body>
    
<div id="categoryLeftColumn">
    
    <c:forEach var="objekatKat" items="${objekatKategorije}">

        <c:choose>
            <c:when test="${objekatKat.naziv_Kategorije == selektovanaKategorija.naziv_Kategorije}">
                <div class="categoryButton" id="selectedCategory">
                    <span class="categoryText">
                        ${objekatKat.naziv_Kategorije}
                    </span>
                </div>
            </c:when>
            <c:otherwise>
                <a href="kategorija?${objekatKat.id_Kategorija}" class="categoryButton">
                    <div class="categoryText">
                        ${objekatKat.naziv_Kategorije}
                    </div>
                </a>
            </c:otherwise>
        </c:choose>

    </c:forEach>

</div>
            <div id="categoryRightColumn">
                <p id="categoryTitle">${selektovanaKategorija.naziv_Kategorije}</p>

                <table id="productTable">
                   <c:forEach var="proizvod" items="${kategorijaProizvoda}" varStatus="iter">

        <tr class="${((iter.index % 2) == 0) ? 'lightBlue' : 'white'}">
            <td>
                ${proizvod.ime_Proizvoda}
                <br>
                <span class="smallText">${proizvod.opis_Sastojaka}</span>
            </td>
            <td>
                RSD ${proizvod.cena} / 1
            </td>
            <td>
                <form action="<c:url value='ubaciUKorpu'/>" method="post">
                    <input type="hidden"
                           name="prozivodId"
                           value="${proizvod.id_Proizvod}">
                    <input type="submit"
                           value="Dodaj u korpu">
                </form>
            </td>
        </tr>

    </c:forEach>
                </table>
            </div>

            
     
    </body>
</html>

web/WEB-INF/view/korpa.jsp
<!DOCTYPE html>

<c:set var="view" value="/korpa" scope="session"/>
<html>
   <body>

            <div id="centerColumn">

                <p>Vasa korpa sadrzi ${korpa.numberOfItems} proizvoda.</p>
                <div id="actionBar">
        <%-- clear cart widget --%>
        <c:if test="${!empty korpa && korpa.numberOfItems != 0}">

            <c:url var="url" value="pogledajKorpu">
                <c:param name="obrisi" value="true"/>
            </c:url>

            <a href="${url}" class="bubble hMargin">Obrisi korpu</a>
        </c:if>

        <%-- continue shopping widget --%>
        <c:set var="value">
            <c:choose>
                <%-- if 'selectedCategory' session object exists, send user to previously viewed category --%>
                <c:when test="${!empty selektovanaKategorija}">
                    kategorija
                </c:when>
                <%-- otherwise send user to welcome page --%>
                <c:otherwise>
                    index.jsp
                </c:otherwise>
            </c:choose>
        </c:set>

        <c:url var="url" value="${value}"/>
        <a href="${url}" class="bubble hMargin">Nastavi kupovinu</a>

        <%-- checkout widget --%>
        <c:if test="${!empty korpa && korpa.numberOfItems != 0}">
            <a href="<c:url value='racun'/>" class="bubble hMargin">Uzmite racun</a>
        </c:if>
    </div>
            <c:if test="${!empty korpa && korpa.numberOfItems != 0}">

      <h4 id="subtotal">Total:
          ${korpa.subtotal}
      </h4>

      <table id="cartTable">

        <tr class="header">
            <th>Ime proizvoda</th>
            <th>Cena po komadu</th>
            <th>Kolicina</th>
            
        </tr>

        <c:forEach var="cartItem" items="${korpa.items}" varStatus="iter">

          <c:set var="product" value="${cartItem.product}"/>

          <tr class="${((iter.index % 2) == 0) ? 'lightBlue' : 'white'}">
            <td>${product.ime_Proizvoda}</td>

            <td>
                <span class="smallText">
                    ${product.cena}
                    </span>
               <br>
                 
            </td>

            <td>
                <form action="<c:url value='updateKorpu'/>" method="post">
                    <input type="hidden"
                           name="id_Proizvod"
                           value="${product.id_Proizvod}">
                    <input type="text"
                           maxlength="2"
                           size="2"
                           value="${cartItem.kolicina}"
                           name="kolicina"
                           style="margin:5px">
                    <input type="submit"
                           name="submit"
                           value="Osvezi korpu">
                </form>
            </td>
          </tr>

        </c:forEach>

      </table>

    </c:if>
             </div>

           
   
    </body>
</html>

web/WEB-INF/view/potvrda.jsp
<!DOCTYPE html>
<html>
   <body>

           <div id="singleColumn">

    <p id="confirmationText">
        <strong>Uspesna kupovina</strong>
    </p>

    <div class="summaryColumn" >

        <table id="orderSummaryTable" class="detailsTable">
            <tr class="header">
                <th colspan="3">Ovo ste narucili</th>
            </tr>

            <tr class="tableHeading">
                <td>Proizvod</td>
                <td>Kolicina</td>
                <td>Cena</td>
            </tr>

            <c:forEach var="orderedProduct" items="${naruceniProizvodi}" varStatus="iter">

                <tr class="${((iter.index % 2) != 0) ? 'lightBlue' : 'white'}">
                    <td>
                        ${proizvodi[iter.index].ime_Proizvoda}
                    </td>
                    <td class="quantityColumn">
                        ${orderedProduct.kolicina}
                    </td>
                    <td class="confirmationPriceColumn">
                       ${proizvodi[iter.index].cena * orderedProduct.kolicina}
                    </td>
                </tr>

            </c:forEach>

            <tr class="lightBlue"><td colspan="3" style="padding: 0 20px"><hr></td></tr>

            <tr class="lightBlue">
                <td colspan="2" id="totalCellLeft"><strong>Total:</strong></td>
                <td id="totalCellRight">
                    ${porudzbina.racunPorudzbine}</td>
            </tr>

            <tr class="lightBlue"><td colspan="3" style="padding: 0 20px"><hr></td></tr>

            <tr class="lightBlue">
                <td colspan="3" id="dateProcessedRow"><strong>Datuma:</strong>
                    ${porudzbina.vremekreiranjaPorudzbine}"
                                   </td>
            </tr>
        </table>

    </div>

    <div class="summaryColumn" >

        <table id="deliveryAddressTable" class="detailsTable">
            <tr class="header">
                <th colspan="3">Adresa:</th>
            </tr>

            <tr>
                <td colspan="3" class="lightBlue">
                    <strong>Adresa:</strong> ${kupac.adresa_Kupca}
                    <br>
                    <strong>Telefon:</strong> ${kupac.broj_Telefona}
                </td>
            </tr>
        </table>
    </div>
</div>

            
      </body>
</html>

web/WEB-INF/view/racun.jsp
<!DOCTYPE html>
<c:set var="view" value="/racun" scope="session"/>
<script src="js/jquery.validate.js" type="text/javascript"></script>
<html>
   <body>

       <script type="text/javascript">

    $(document).ready(function(){
        $("#checkoutForm").validate({
            rules: {
                
                phone: {
                    required: true,
                    number: true,
                    minlength: 9
                },
                address: {
                    required: true
                }
            }
        });
    });
</script>


<%-- HTML markup starts below --%>

<div id="singleColumn">

    <h2>Racun</h2>

    

    <c:if test="${!empty validationErrorFlag}">
        <p class="error"><font color="red">Greska u racunu</font></p>
    </c:if>

    <form id="checkoutForm" action="<c:url value='kupovina'/>" method="post">
        <table id="checkoutTable">
          <c:if test="${!empty validationErrorFlag}">
            <tr>
                <td colspan="2" style="text-align:left">
                    <span class="error smallText"><font color="red">Molimo vas popravite unose</font>
                      <c:if test="${!empty phoneError}">
                          <br><span class="indent"><font color="red">Telefon pogresno unet</font></span>
                      </c:if>
                      <c:if test="${!empty addressError}">
                      <br><span class="indent"><font color="red">Adresa pogresno uneta</font></span>
                      </c:if>
                    </span>
                </td>
            </tr>
          </c:if>
            <tr>
                <td><label for="phone">Telefon:</label></td>
                <td class="inputField">
                    <input type="text"
                           size="31"
                           maxlength="16"
                           id="phone"
                           name="phone"
                           value="${param.phone}">
                </td>
            </tr>
            <tr>
                <td><label for="address">Adresa:</label></td>
                <td class="inputField">
                    <input type="text"
                           size="31"
                           maxlength="45"
                           id="address"
                           name="address"
                           value="${param.address}">

                    <br>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" value="Potvrdi">
                </td>
            </tr>
        </table>
    </form>

    <div id="infoBox">

        

        <table id="priceBox">
            <tr>
                <td class="total">Ukupno:</td>
                <td class="total checkoutPriceColumn">
                ${korpa.total}</td>
            </tr>
        </table>
    </div>
</div>
      </body>
</html>